# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Backend Deploy (lu1backend)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/main_lu1backend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
        
      - name: Install & Build (backend only)
        working-directory: backend
        run: |
          npm ci
          npm run build
          mkdir deploy
          cp package.json package-lock.json deploy/
          cp -r dist deploy/
          # optioneel voorbeeld env (geen echte secrets!)
          if [ -f .env.example ]; then cp .env.example deploy/; fi

      - name: Upload artifact (deploy folder)
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: backend/deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact
          path: backend
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7BB1D64535984690BF7890AE97A11C81 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DC3F92A6CE9148DDB75EF179777755C9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8EFB0DCACC504253A2EE5FA60F9CF349 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lu1backend'
          slot-name: 'Production'
          package: backend

      - name: Done
        run: echo "Backend deployment complete"
          